# Generated by Django 2.1.5 on 2019-01-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(max_length=50)),
                ('dep_name', models.CharField(max_length=50)),
            ],
        ),
    ]
