# Generated by Django 2.1.5 on 2019-01-29 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personinfo.PersonApp'),
        ),
    ]
